#!/usr/bin/env python3
"""Generate paper tables from authoritative JSON data sources.

Reads experiment outputs and generates markdown table files in docs/tables/.
Each generated file includes a provenance comment citing the script and data source.

Usage:
    uv run scripts/generate_paper_tables.py
    uv run scripts/generate_paper_tables.py --update-paper   # replace tables in paper between markers
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUTPUTS = ROOT / "outputs"
TABLES_DIR = ROOT / "docs" / "tables"
PAPER_PATH = ROOT / "docs" / "steering_diversity_paper.md"


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def fmt_p(p: float) -> str:
    """Format p-value for display."""
    if p < 0.001:
        return "< 0.001"
    return f"{p:.3f}"


def fmt_f(v: float, decimals: int = 3) -> str:
    """Format float with fixed decimals."""
    return f"{v:.{decimals}f}"


def load_json(path: Path) -> Any:
    with open(path) as f:
        return json.load(f)


def write_table(name: str, content: str, data_source: str) -> Path:
    """Write a generated table file with provenance header. Returns the path."""
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    header = (
        f"<!-- Generated by: scripts/generate_paper_tables.py -->\n"
        f"<!-- Data source: {data_source} -->\n\n"
    )
    path = TABLES_DIR / f"{name}.md"
    path.write_text(header + content + "\n")
    print(f"  Wrote {path.relative_to(ROOT)}")
    return path


def compute_within_prompt_cosine(embeddings_path: Path) -> list[dict[str, float]]:
    """Compute within-prompt mean pairwise cosine distance per scale from embeddings."""
    from sklearn.metrics.pairwise import cosine_distances

    data = np.load(embeddings_path)
    embeddings = data["embeddings"]
    scales = data["scales"]
    prompt_indices = data["prompt_indices"]

    unique_scales = sorted(set(float(s) for s in scales))
    unique_prompts = sorted(set(int(p) for p in prompt_indices))

    results: list[dict[str, float]] = []
    for scale in unique_scales:
        prompt_dists: list[float] = []
        for prompt_idx in unique_prompts:
            mask = (prompt_indices == prompt_idx) & np.isclose(scales, scale)
            group_embs = embeddings[mask]
            if group_embs.shape[0] > 1:
                cd = cosine_distances(group_embs)
                triu = np.triu_indices(group_embs.shape[0], k=1)
                prompt_dists.append(float(np.mean(cd[triu])))
        arr = np.array(prompt_dists)
        results.append({
            "scale": scale,
            "within_prompt_mean": float(arr.mean()),
            "within_prompt_se": float(arr.std(ddof=1) / np.sqrt(len(arr))),
        })
    return results


# ---------------------------------------------------------------------------
# Table generators — each returns the markdown table body (no provenance header)
# ---------------------------------------------------------------------------

def gen_happy_full_stats() -> str:
    """Section 4.1.1 — happy_full statistical tests."""
    stats = load_json(OUTPUTS / "happy_full" / "stats.json")
    me = stats["mixed_effects"]
    sp = stats["spearman_effect_size"]
    hb = stats["holm_bonferroni"]

    best_metric = min(hb, key=lambda k: hb[k]["raw_p"])
    best_raw = hb[best_metric]["raw_p"]
    best_adj = hb[best_metric]["adjusted_p"]

    table = (
        "| Test | Statistic | p-value | Significant? |\n"
        "| --- | --- | --- | :---: |\n"
        f"| Mixed-effects model (primary) | beta = {fmt_f(me['beta'], 4)} | {fmt_p(me['p_value'])} | No |\n"
        f"| Spearman rho (effect size) | rho = {fmt_f(sp['rho'], 3)} | {fmt_p(sp['p_value'])} | No |\n"
        f"| Page's L (all 6 metrics, Holm-Bonferroni) | best raw p = {fmt_f(best_raw, 3)} ({best_metric}) | adj p = {fmt_f(best_adj, 3)} | No |"
    )

    write_table("happy_full_stats", table, "outputs/happy_full/stats.json")
    return table


def gen_happy_full_metrics() -> str:
    """Section 4.1.1 — happy_full per-scale diversity metrics."""
    metrics = load_json(OUTPUTS / "happy_full" / "metrics.json")

    lines = [
        "| Scale | Clusters | Noise ratio | Mean pairwise cosine dist | Cluster entropy |",
        "| ----- | -------- | ----------- | :-----------------------: | :-------------: |",
    ]
    for m in metrics:
        lines.append(
            f"| {m['scale']:.1f}   | {m['num_clusters']}       | {fmt_f(m['noise_ratio'], 3)}       |"
            f"           {fmt_f(m['mean_pairwise_cosine_distance'], 3)}           |"
            f"      {fmt_f(m['cluster_entropy'], 2)}       |"
        )
    table = "\n".join(lines)
    write_table("happy_full_metrics", table, "outputs/happy_full/metrics.json")
    return table


def gen_happy_recon_within_vs_pooled() -> str:
    """Section 4.1.2 — happy_recon within-prompt vs pooled decomposition."""
    breakdown = load_json(OUTPUTS / "happy_recon" / "cosine_distance_breakdown.json")

    lines = [
        "| Scale | Within-prompt (mean +/- SE) | Pooled (cross-prompt included) |",
        "| ----- | :-------------------------: | :----------------------------: |",
    ]
    for entry in breakdown:
        within = f"{fmt_f(entry['within_prompt_mean_cosine_distance'], 3)} +/- {fmt_f(entry['within_prompt_se'], 3)}"
        pooled = fmt_f(entry['pooled_mean_cosine_distance'], 3)
        lines.append(f"| {entry['scale']:.1f}   |       {within}       |             {pooled}              |")
    table = "\n".join(lines)
    write_table(
        "happy_recon_within_vs_pooled", table,
        "outputs/happy_recon/cosine_distance_breakdown.json",
    )
    return table


def gen_happy_recon_stats() -> str:
    """Section 4.1.2 — happy_recon statistical tests."""
    stats = load_json(OUTPUTS / "happy_recon" / "stats.json")
    me = stats["mixed_effects"]
    sp = stats["spearman_effect_size"]
    hb = stats["holm_bonferroni"]

    noise_adj_p = hb["noise_ratio"]["adjusted_p"]

    table = (
        "| Test | Statistic | p-value | Significant? |\n"
        "| --- | --- | --- | :---: |\n"
        f"| Mixed-effects (primary) | beta = {fmt_f(me['beta'], 4)} | {fmt_p(me['p_value'])} | No |\n"
        f"| Spearman rho | rho = {fmt_f(sp['rho'], 3)} | {fmt_p(sp['p_value'])} | No |\n"
        f"| Page's L (noise_ratio, Holm-corrected) | — | {fmt_f(noise_adj_p, 3)} | Yes\\* |"
    )
    write_table("happy_recon_stats", table, "outputs/happy_recon/stats.json")
    return table


def gen_experiment_metrics(name: str) -> str:
    """Sections 4.2/4.3 — per-scale metrics with within-prompt cosine distance."""
    metrics = load_json(OUTPUTS / name / "metrics.json")
    within = compute_within_prompt_cosine(OUTPUTS / name / "embeddings.npz")

    lines = [
        "| Scale | Clusters | Cosine dist (pooled) | Within-prompt cosine dist | Noise ratio |",
        "| ----- | -------- | :------------------: | :-----------------------: | :---------: |",
    ]
    for m, w in zip(metrics, within):
        lines.append(
            f"| {m['scale']:.1f}   | {m['num_clusters']}        |"
            f"        {fmt_f(m['mean_pairwise_cosine_distance'], 3)}         |"
            f"           {fmt_f(w['within_prompt_mean'], 2)}            |"
            f"    {fmt_f(m['noise_ratio'], 2)}     |"
        )
    table = "\n".join(lines)
    write_table(
        f"{name}_metrics", table,
        f"outputs/{name}/metrics.json, outputs/{name}/embeddings.npz",
    )
    return table


def gen_experiment_stats(name: str) -> str:
    """Sections 4.2/4.3 — statistical tests for an experiment."""
    stats = load_json(OUTPUTS / name / "stats.json")
    me = stats["mixed_effects"]
    sp = stats["spearman_effect_size"]
    hb = stats["holm_bonferroni"]

    me_sig = "Yes" if me["p_value"] < 0.05 else "No"
    sp_sig = "Yes" if sp["p_value"] < 0.05 else "No"

    lines = [
        "| Test | Statistic | p-value | Significant? |",
        "| --- | --- | --- | :---: |",
        f"| Mixed-effects (primary) | beta = {fmt_f(me['beta'], 3)} | {fmt_p(me['p_value'])} | {me_sig} |",
        f"| Spearman rho | rho = {fmt_f(sp['rho'], 3)} | {fmt_p(sp['p_value'])} | {sp_sig} |",
    ]
    for metric_name, result in sorted(hb.items(), key=lambda kv: kv[1]["raw_p"]):
        if result["significant"]:
            lines.append(
                f"| Page's L ({metric_name}, Holm-corrected) | — | {fmt_p(result['adjusted_p'])} | Yes |"
            )
    table = "\n".join(lines)
    write_table(f"{name}_stats", table, f"outputs/{name}/stats.json")
    return table


def gen_cross_experiment() -> str:
    """Section 4.4 — cross-experiment comparison table."""
    # happy_recon
    hr_bd = load_json(OUTPUTS / "happy_recon" / "cosine_distance_breakdown.json")
    hr_stats = load_json(OUTPUTS / "happy_recon" / "stats.json")
    hr_p0 = hr_bd[0]["pooled_mean_cosine_distance"]
    hr_p4 = next(e["pooled_mean_cosine_distance"] for e in hr_bd if e["scale"] == 4.0)
    hr_pct = (1 - hr_p4 / hr_p0) * 100
    hr_me = hr_stats["mixed_effects"]
    hr_within = f"None (beta ≈ 0, p = {fmt_f(hr_me['p_value'], 2)})"

    # style_full
    sf_m = load_json(OUTPUTS / "style_full" / "metrics.json")
    sf_stats = load_json(OUTPUTS / "style_full" / "stats.json")
    sf_p0 = next(m["mean_pairwise_cosine_distance"] for m in sf_m if m["scale"] == 0.0)
    sf_p4 = next(m["mean_pairwise_cosine_distance"] for m in sf_m if m["scale"] == 4.0)
    sf_pct = (1 - sf_p4 / sf_p0) * 100
    sf_me = sf_stats["mixed_effects"]
    sf_within = f"Mild (beta = {fmt_f(sf_me['beta'], 3)}, p = {fmt_f(sf_me['p_value'], 3)})"

    # creativity_full
    cf_m = load_json(OUTPUTS / "creativity_full" / "metrics.json")
    cf_p0 = next(m["mean_pairwise_cosine_distance"] for m in cf_m if m["scale"] == 0.0)
    cf_p4 = next(m["mean_pairwise_cosine_distance"] for m in cf_m if m["scale"] == 4.0)
    cf_pct = (1 - cf_p4 / cf_p0) * 100
    cf_within_data = compute_within_prompt_cosine(OUTPUTS / "creativity_full" / "embeddings.npz")
    cf_wv = [w["within_prompt_mean"] for w in cf_within_data[:5]]  # scales 0-4
    cf_within = f"None (flat {fmt_f(min(cf_wv), 2)}–{fmt_f(max(cf_wv), 2)})"

    lines = [
        "| Experiment | Model | Concept | Pooled diversity reduction (scale 0→4) | Within-prompt effect |",
        "| :--- | :--- | :--- | :---: | :---: |",
        f"| happy_recon | Qwen2.5-1.5B | happy | {fmt_f(hr_p0, 2)} → {fmt_f(hr_p4, 2)} ({hr_pct:.0f}%) | {hr_within} |",
        f"| style_full | Qwen2.5-1.5B | style | {fmt_f(sf_p0, 2)} → {fmt_f(sf_p4, 2)} ({sf_pct:.0f}%) | {sf_within} |",
        f"| creativity_full | Llama-3-8B | creativity | {fmt_f(cf_p0, 2)} → {fmt_f(cf_p4, 2)} ({cf_pct:.0f}%) | {cf_within} |",
    ]
    table = "\n".join(lines)
    write_table(
        "cross_experiment_comparison", table,
        "outputs/{happy_recon,style_full,creativity_full}/{metrics,stats}.json, outputs/*/embeddings.npz",
    )
    return table


def gen_eval_awareness_baseline() -> str:
    """Section 4.5 — Qwen3-32B eval awareness baseline (AUC/Brier/ECE)."""
    score_path = ROOT / "eval_awareness" / "run_summaries" / "score_table.txt"
    if not score_path.exists():
        print("  SKIP: eval_awareness/run_summaries/score_table.txt not found")
        return ""

    # Parse the fixed-width score table for qwen/qwen3-32b
    for line in score_path.read_text().splitlines():
        if "qwen3-32b" in line and "30b" not in line and "397b" not in line:
            parts = line.split()
            # Format: model  AUC Brier ECE  AUC Brier ECE  AUC Brier ECE
            # (All, Chat, Agentic)
            # The model name may have slashes, so find the numeric columns from the right
            nums = [p for p in parts if re.match(r"^0\.\d+$", p)]
            if len(nums) == 9:
                all_auc, all_brier, all_ece = nums[0], nums[1], nums[2]
                chat_auc, chat_brier, chat_ece = nums[3], nums[4], nums[5]
                agent_auc, agent_brier, agent_ece = nums[6], nums[7], nums[8]

                table_lines = [
                    "| Subset | AUC | Brier | ECE |",
                    "| --- | :---: | :---: | :---: |",
                    f"| All | {all_auc} | {all_brier} | {all_ece} |",
                    f"| Chat | {chat_auc} | {chat_brier} | {chat_ece} |",
                    f"| Agentic | {agent_auc} | {agent_brier} | {agent_ece} |",
                ]
                table = "\n".join(table_lines)
                write_table(
                    "eval_awareness_qwen3_32b", table,
                    "eval_awareness/run_summaries/score_table.txt",
                )
                return table

    print("  SKIP: qwen3-32b row not found in score_table.txt")
    return ""


def _count_field(results: list[dict], field: str) -> dict[str, int]:
    """Count occurrences of Yes/No/Maybe/ERROR for a field in results."""
    counts: dict[str, int] = {"Yes": 0, "No": 0, "Maybe": 0}
    for r in results:
        val = r.get(field, "ERROR")
        if val in counts:
            counts[val] += 1
    return counts


def gen_ms_triggers_unsteered() -> str:
    """Section 4.5.1 — unsteered MS triggers baseline (n=50)."""
    data = load_json(OUTPUTS / "steering_verification" / "unsteered_hypothetical_n50.json")
    aw = data["awareness_counts"]
    co = data["compliance_counts"]
    hyp = _count_field(data["results"], "hypothetical")
    n = sum(v for k, v in aw.items() if k != "ERROR")

    def row(label: str, counts: dict[str, int]) -> str:
        total = sum(v for k, v in counts.items() if k != "ERROR")
        return (
            f"| {label} | {counts['Yes']} ({counts['Yes']*100//total}%) "
            f"| {counts['No']} ({counts['No']*100//total}%) "
            f"| {counts['Maybe']} ({counts['Maybe']*100//total}%) |"
        )

    lines = [
        "| Metric | Yes | No | Maybe |",
        "| --- | :---: | :---: | :---: |",
        row("Model awareness", aw),
        row("Hypothetical recognition", hyp),
        row("Task compliance", co),
    ]
    table = "\n".join(lines)
    write_table(
        "ms_triggers_unsteered", table,
        "outputs/steering_verification/unsteered_hypothetical_n50.json",
    )
    return table


def gen_ms_triggers_steered() -> str:
    """Section 4.5.1 — steered MS triggers results (α=0.3, n=36 judged)."""
    data = load_json(OUTPUTS / "steering_verification" / "steered_hypothetical_n50.json")
    aw = data["awareness_counts"]
    co = data["compliance_counts"]
    hyp = _count_field(data["results"], "hypothetical")
    # n_judged excludes errors
    n_judged = sum(v for k, v in aw.items() if k != "ERROR")

    def row(label: str, counts: dict[str, int]) -> str:
        total = sum(v for k, v in counts.items() if k != "ERROR")
        if total == 0:
            return f"| {label} | — | — | — |"
        return (
            f"| {label} | {counts['Yes']} ({counts['Yes']*100//total}%) "
            f"| {counts['No']} ({counts['No']*100//total}%) "
            f"| {counts['Maybe']} ({counts['Maybe']*100//total}%) |"
        )

    lines = [
        "| Metric | Yes | No | Maybe |",
        "| --- | :---: | :---: | :---: |",
        row("Model awareness", aw),
        row("Hypothetical recognition", hyp),
        row("Task compliance", co),
    ]
    table = "\n".join(lines)
    write_table(
        "ms_triggers_steered", table,
        "outputs/steering_verification/steered_hypothetical_n50.json",
    )
    return table


def gen_ms_triggers_comparison() -> str:
    """Section 4.5.1 — comparison: unsteered vs steered vs MS paper."""
    unst = load_json(OUTPUTS / "steering_verification" / "unsteered_hypothetical_n50.json")
    strd = load_json(OUTPUTS / "steering_verification" / "steered_hypothetical_n50.json")

    un_aw = unst["awareness_counts"]
    un_co = unst["compliance_counts"]
    un_n = sum(v for k, v in un_aw.items() if k != "ERROR")

    st_aw = strd["awareness_counts"]
    st_co = strd["compliance_counts"]
    st_n = sum(v for k, v in st_aw.items() if k != "ERROR")

    un_aware_pct = (un_aw["Yes"] + un_aw.get("Maybe", 0)) * 100 // un_n
    un_comply_pct = un_co["Yes"] * 100 // un_n
    st_aware_pct = (st_aw["Yes"] + st_aw.get("Maybe", 0)) * 100 // st_n
    st_comply_pct = st_co["Yes"] * 100 // st_n

    # MS paper values are external reference data (hardcoded from Abdelnabi et al., 2025)
    lines = [
        "| Metric | Unsteered (n=50) | Steered α=0.3 (n=36) | MS paper unsteered | MS paper α=0.25 |",
        "| --- | :---: | :---: | :---: | :---: |",
        f"| Awareness (Yes+Maybe) | {un_aware_pct}% | {st_aware_pct}% | 24% | 10% |",
        f"| Compliance (Yes) | {un_comply_pct}% | {st_comply_pct}% | 34% | 50% |",
    ]
    table = "\n".join(lines)
    write_table(
        "ms_triggers_comparison", table,
        "outputs/steering_verification/{un,}steered_hypothetical_n50.json + Abdelnabi et al. 2025 Table values",
    )
    return table


def gen_coverage_gain_n100() -> str:
    """Section 4.6.1 — coverage gain test (n=100, HumanEval+)."""
    cg = load_json(OUTPUTS / "passk_main_v1" / "code" / "coverage_gain_test.json")

    lines = [
        "| k | Δ coverage gain | SE | p-value | sig |",
        "|--:|:--:|:--:|:--:|:--:|",
    ]
    for r in cg["per_k_results"]:
        k = r["k"]
        is_primary = (k == cg["primary_k"])
        delta = fmt_f(r["delta_cg"], 3)
        se = fmt_f(r["se"], 3)
        p = fmt_f(r["p_value"], 4)
        sig = "\\*" if r["significant"] else ""
        if is_primary:
            lines.append(f"| **{k}** | **{delta}** | **{se}** | **{p}** | **{sig}** |")
        else:
            lines.append(f"| {k} | {delta} | {se} | {p} | {sig} |")
    table = "\n".join(lines)
    write_table(
        "coverage_gain_n100", table,
        "outputs/passk_main_v1/code/coverage_gain_test.json",
    )
    return table


def gen_qwq_passk() -> str:
    """Section 4.6.3 — QwQ-32B pass@k results (BigCodeBench, n=5, 150 problems)."""
    curves = load_json(OUTPUTS / "passk_qwq_v1" / "code" / "bigcodebench" / "pass_at_k_curves_merged.json")

    # Find unsteered (scale 0.0) and steered (scale 0.25)
    unst = next(c for c in curves if c["scale"] == 0.0)
    strd = next(c for c in curves if c["scale"] == 0.25)

    lines = [
        "| Metric | Unsteered (α=0) | Steered (α=−0.25) | Difference |",
        "| --- | :---: | :---: | :---: |",
    ]
    for k_str in sorted(unst["pass_at_k_plus"].keys(), key=int):
        u_val = unst["pass_at_k_plus"][k_str]
        s_val = strd["pass_at_k_plus"][k_str]
        diff = s_val - u_val
        lines.append(
            f"| pass@{k_str} | {fmt_f(u_val, 3)} | {fmt_f(s_val, 3)} | {fmt_f(diff, 3)} |"
        )
    table = "\n".join(lines)
    write_table(
        "qwq_passk", table,
        "outputs/passk_qwq_v1/code/bigcodebench/pass_at_k_curves_merged.json",
    )
    return table


def gen_qwq_coverage_gain() -> str:
    """Section 4.6.3 — QwQ-32B coverage gain test."""
    cg = load_json(OUTPUTS / "passk_qwq_v1" / "code" / "bigcodebench" / "coverage_gain_test_merged.json")

    lines = [
        "| k | Δ coverage gain | SE | p-value | sig |",
        "| --- | :---: | :---: | :---: | :---: |",
    ]
    for r in cg["per_k_results"]:
        sig = "\\*" if r["significant"] else ""
        lines.append(
            f"| {r['k']} | {'+' if r['delta_cg'] >= 0 else ''}{fmt_f(r['delta_cg'], 4)} "
            f"| {fmt_f(r['se'], 4)} | {fmt_f(r['p_value'], 3)} | {sig} |"
        )
    table = "\n".join(lines)
    write_table(
        "qwq_coverage_gain", table,
        "outputs/passk_qwq_v1/code/bigcodebench/coverage_gain_test_merged.json",
    )
    return table


def gen_passk_preliminary() -> str:
    """Section 4.6 — preliminary pass@k (n=10, unsteered vs steered)."""
    unst_path = OUTPUTS / "test_unsteered_full" / "humaneval" / "pass_at_k.json"
    strd_curves = load_json(OUTPUTS / "passk_test_steered" / "code" / "pass_at_k_curves.json")
    strd = strd_curves[0]

    if not unst_path.exists():
        print("  SKIP: outputs/test_unsteered_full/humaneval/pass_at_k.json not found")
        print("  Run: uv run scripts/eval/extract_preliminary_passk.py")
        return ""
    unst = load_json(unst_path)

    lines = [
        "| Metric | Unsteered (α=0) | Steered (α=2) | Δ | 95% CI | Paired t | p |",
        "|--------|:-:|:-:|:-:|:-:|:-:|:-:|",
    ]
    for variant in ["base", "plus"]:
        unst_k = unst[f"pass_at_k_{variant}"]
        strd_k = strd[f"pass_at_k_{variant}"]
        for k_str in sorted(unst_k.keys(), key=int):
            if k_str not in strd_k:
                continue
            u = unst_k[k_str]
            s = strd_k[k_str]
            delta = s - u

            # Compute paired t-test from per-problem data
            from src.pass_at_k import pass_at_k as pak
            import scipy.stats as st
            n_samp = unst["n_samples_per_problem"]
            k_int = int(k_str)
            status_key = f"per_problem_{variant}"
            u_scores = np.array([pak(p["n"], p["c"], k_int) for p in unst[status_key]])
            s_scores = np.array([pak(p["n"], p["c"], k_int) for p in strd[f"per_problem_{variant}"]])
            diffs = s_scores - u_scores
            se = float(np.std(diffs, ddof=1) / np.sqrt(len(diffs)))
            ci_95 = 1.96 * se
            t_stat, p_val = st.ttest_rel(s_scores, u_scores)

            p_str = f"**{fmt_f(p_val, 3)}**" if p_val < 0.05 else fmt_f(p_val, 3)
            label = f"**pass@{k_str} ({variant})**"
            lines.append(
                f"| {label} | {fmt_f(u, 3)} | {fmt_f(s, 3)} | {fmt_f(delta, 3)} "
                f"| ±{fmt_f(ci_95, 3)} | {fmt_f(t_stat, 2)} | {p_str} |"
            )
    table = "\n".join(lines)
    write_table(
        "passk_preliminary", table,
        "outputs/test_unsteered_full/humaneval/pass_at_k.json, "
        "outputs/passk_test_steered/code/pass_at_k_curves.json",
    )
    return table


def gen_power_analysis() -> str:
    """Section 4.6.2 — simulated power analysis."""
    pa_path = OUTPUTS / "passk_test_steered" / "code" / "power_analysis.json"
    if not pa_path.exists():
        print("  SKIP: outputs/passk_test_steered/code/power_analysis.json not found")
        print("  Run: uv run scripts/eval/power_analysis_passk.py")
        return ""
    pa = load_json(pa_path)

    lines = [
        "| n (samples/problem) | Predicted Δpass@1 (mean ± 95% CI) "
        "| Predicted Δpass@10 (mean ± 95% CI) | Would separate? |",
        "|:---:|:---:|:---:|:---:|",
    ]
    for r in pa["per_n_results"]:
        d1 = r["predictions"]["delta_pass_at_1"]
        d10 = r["predictions"]["delta_pass_at_10"]
        sep = "**Yes**" if r["separated"] else "No"
        lines.append(
            f"| {r['n']} | {fmt_f(d1['mean'], 3)} ± {fmt_f(d1['ci_95'], 3)} "
            f"| {fmt_f(d10['mean'], 3)} ± {fmt_f(d10['ci_95'], 3)} | {sep} |"
        )
    table = "\n".join(lines)
    write_table(
        "power_analysis", table,
        "outputs/passk_test_steered/code/power_analysis.json",
    )
    return table


def gen_passk_n100() -> str:
    """Section 4.6.1 — pass@k curves for n=100 (used by coverage gain section context).

    Not a table in the paper currently, but the pass@1 values are cited inline.
    Generated for reference/verification.
    """
    curves = load_json(OUTPUTS / "passk_main_v1" / "code" / "pass_at_k_curves.json")
    unst = next(c for c in curves if c["scale"] == 0.0)
    strd = next(c for c in curves if c["scale"] == 2.0)

    lines = [
        "| k | Unsteered (base) | Steered α=2 (base) | Unsteered (plus) | Steered α=2 (plus) |",
        "| --: | :---: | :---: | :---: | :---: |",
    ]
    for k_str in sorted(unst["pass_at_k_base"].keys(), key=int):
        lines.append(
            f"| {k_str} | {fmt_f(unst['pass_at_k_base'][k_str], 3)} "
            f"| {fmt_f(strd['pass_at_k_base'][k_str], 3)} "
            f"| {fmt_f(unst['pass_at_k_plus'][k_str], 3)} "
            f"| {fmt_f(strd['pass_at_k_plus'][k_str], 3)} |"
        )
    table = "\n".join(lines)
    write_table(
        "passk_n100_curves", table,
        "outputs/passk_main_v1/code/pass_at_k_curves.json",
    )
    return table


# ---------------------------------------------------------------------------
# Paper update: replace tables between markers
# ---------------------------------------------------------------------------

def update_paper(tables: dict[str, str]) -> None:
    """Replace tables in the paper between <!-- BEGIN/END GENERATED TABLE --> markers."""
    text = PAPER_PATH.read_text()
    replacements = 0

    for name, content in tables.items():
        pattern = (
            rf"(<!-- BEGIN GENERATED TABLE: {re.escape(name)} -->)\n"
            r".*?"
            rf"\n(<!-- END GENERATED TABLE: {re.escape(name)} -->)"
        )
        replacement = rf"\1\n{content}\n\2"
        new_text, count = re.subn(pattern, replacement, text, flags=re.DOTALL)
        if count > 0:
            text = new_text
            replacements += count
            print(f"  Updated table '{name}' in paper")

    if replacements > 0:
        PAPER_PATH.write_text(text)
        print(f"\n  Updated {replacements} table(s) in {PAPER_PATH.relative_to(ROOT)}")
    else:
        print(
            "\n  No markers found in paper. Add markers like:\n"
            "  <!-- BEGIN GENERATED TABLE: table_name -->\n"
            "  ... table content ...\n"
            "  <!-- END GENERATED TABLE: table_name -->"
        )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate paper tables from data sources")
    parser.add_argument(
        "--update-paper", action="store_true",
        help="Replace tables between markers in the paper",
    )
    args = parser.parse_args()

    tables: dict[str, str] = {}

    print("Generating tables...\n")

    # Section 4.1.1 — happy_full
    print("Section 4.1.1: happy_full")
    tables["happy_full_stats"] = gen_happy_full_stats()
    tables["happy_full_metrics"] = gen_happy_full_metrics()

    # Section 4.1.2 — happy_recon
    print("\nSection 4.1.2: happy_recon")
    tables["happy_recon_within_vs_pooled"] = gen_happy_recon_within_vs_pooled()
    tables["happy_recon_stats"] = gen_happy_recon_stats()

    # Section 4.2 — style_full
    print("\nSection 4.2: style_full")
    tables["style_full_metrics"] = gen_experiment_metrics("style_full")
    tables["style_full_stats"] = gen_experiment_stats("style_full")

    # Section 4.3 — creativity_full
    print("\nSection 4.3: creativity_full")
    tables["creativity_full_metrics"] = gen_experiment_metrics("creativity_full")
    tables["creativity_full_stats"] = gen_experiment_stats("creativity_full")

    # Section 4.4 — cross-experiment comparison
    print("\nSection 4.4: cross-experiment comparison")
    tables["cross_experiment_comparison"] = gen_cross_experiment()

    # Section 4.5 — eval awareness baseline
    print("\nSection 4.5: eval awareness baseline")
    tables["eval_awareness_qwen3_32b"] = gen_eval_awareness_baseline()

    # Section 4.5.1 — MS triggers
    print("\nSection 4.5.1: MS triggers")
    tables["ms_triggers_unsteered"] = gen_ms_triggers_unsteered()
    tables["ms_triggers_steered"] = gen_ms_triggers_steered()
    tables["ms_triggers_comparison"] = gen_ms_triggers_comparison()

    # Section 4.6 — preliminary pass@k (n=10)
    print("\nSection 4.6: preliminary pass@k (n=10)")
    tables["passk_preliminary"] = gen_passk_preliminary()

    # Section 4.6.1 — coverage gain (n=100)
    print("\nSection 4.6.1: coverage gain (n=100)")
    tables["coverage_gain_n100"] = gen_coverage_gain_n100()
    tables["passk_n100_curves"] = gen_passk_n100()

    # Section 4.6.2 — power analysis
    print("\nSection 4.6.2: power analysis")
    tables["power_analysis"] = gen_power_analysis()

    # Section 4.6.3 — QwQ-32B
    print("\nSection 4.6.3: QwQ-32B BigCodeBench")
    tables["qwq_passk"] = gen_qwq_passk()
    tables["qwq_coverage_gain"] = gen_qwq_coverage_gain()

    # Remove empty tables (skipped due to missing data)
    tables = {k: v for k, v in tables.items() if v}

    print(f"\nGenerated {len(tables)} tables in {TABLES_DIR.relative_to(ROOT)}/")

    if args.update_paper:
        print("\nUpdating paper...")
        update_paper(tables)


if __name__ == "__main__":
    main()
